---

all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: "{{ SSH_PRIVATE_KEY }}"

    installation_method: archive
    confluent_archive_file_source: https://packages.confluent.io/archive/7.4/confluent-7.4.0.tar.gz

    #### Monitoring Configuration ####
    jmxexporter_enabled: "true"
    jolokia_enabled: "true"

    kafka_broker_custom_listeners: 
      client_plaintext:
        name: "CLIENT_PLAINTEXT"
        port: 9093
        ssl_enabled: "false"
        ssl_mutual_auth_enabled: "false"

zookeeper:
  hosts:
    <zk-host-1>:
    <zk-host-2>:
    <zk-host-3>:

kafka_broker:
  hosts:
    <kb-host-1>: 
    <kb-host-2>: 
    <kb-host-3>: 

schema_registry:
  hosts:
    <sr-host-1>:

kafka_connect:
  vars:
    kafka_connect_plugins_path:
      - /usr/share/java

    kafka_connect_confluent_hub_plugins:
      - confluentinc/kafka-connect-datagen:0.6.3

  hosts:
    <kc-host-1>: